const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS';
const FETCH_BEERS_ERROR = 'FETCH_BEERS_ERROR';
const FETCH_BEERS_REQUEST = 'FETCH_BEERS_REQUEST';

const FETCH_BEER_SUCCESS = 'FETCH_BEER_SUCCESS';
const FETCH_BEER_ERROR = 'FETCH_BEER_ERROR';
const FETCH_BEER_REQUEST = 'FETCH_BEER_REQUEST';

export {
	FETCH_BEERS_SUCCESS,
	FETCH_BEERS_ERROR,
	FETCH_BEERS_REQUEST,

	FETCH_BEER_SUCCESS,
	FETCH_BEER_ERROR,
	FETCH_BEER_REQUEST
}