const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS';
const FETCH_BEERS_ERROR = 'FETCH_BEERS_ERROR';
const FETCH_BEERS_REQUEST = 'FETCH_BEERS_REQUEST';

const FETCH_BEER_SUCCESS = 'FETCH_BEER_SUCCESS';
const FETCH_BEER_ERROR = 'FETCH_BEER_ERROR';
const FETCH_BEER_REQUEST = 'FETCH_BEER_REQUEST';

const FETCH_SEARCH_BEER_SUCCESS = 'FETCH_SEARCHED_BEER_SUCCESS';
const FETCH_SEARCH_BEER_ERROR = 'FETCH_SEARCHED_BEER_ERROR';
const FETCH_SEARCH_BEER_REQUEST = 'FETCH_SEARCHED_BEER_REQUEST';

const FETCH_OTHER_PAGE_SUCCESS = 'FETCH_OTHER_PAGE_SUCCESS';
const FETCH_OTHER_PAGE_ERROR = 'FETCH_OTHER_PAGE_ERROR';
const FETCH_OTHER_PAGE_REQUEST= 'FETCH_OTHER_PAGE_REQUEST';

const BEER_ADDED_TO_FAVOURITE = 'BEER_ADDED_TO_FAVOURITE';

export {
	FETCH_BEERS_SUCCESS,
	FETCH_BEERS_ERROR,
	FETCH_BEERS_REQUEST,

	FETCH_BEER_SUCCESS,
	FETCH_BEER_ERROR,
	FETCH_BEER_REQUEST,

	FETCH_SEARCH_BEER_SUCCESS,
	FETCH_SEARCH_BEER_ERROR,
	FETCH_SEARCH_BEER_REQUEST,

	BEER_ADDED_TO_FAVOURITE
}