const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS';
const FETCH_BEERS_ERROR = 'FETCH_BEERS_ERROR';
const FETCH_BEERS_REQUEST = 'FETCH_BEERS_REQUEST';

const FETCH_BEER_SUCCESS = 'FETCH_BEER_SUCCESS';
const FETCH_BEER_ERROR = 'FETCH_BEER_ERROR';
const FETCH_BEER_REQUEST = 'FETCH_BEER_REQUEST';

const FETCH_SEARCH_BEER_SUCCESS = 'FETCH_SEARCHED_BEER_SUCCESS';
const FETCH_SEARCH_BEER_ERROR = 'FETCH_SEARCHED_BEER_ERROR';
const FETCH_SEARCH_BEER_REQUEST = 'FETCH_SEARCHED_BEER_REQUEST';

const BEER_TOGGLE_FAVOURITE = 'BEER_TOGGLE_FAVOURITE';

export {
	FETCH_BEERS_SUCCESS,
	FETCH_BEERS_ERROR,
	FETCH_BEERS_REQUEST,

	FETCH_BEER_SUCCESS,
	FETCH_BEER_ERROR,
	FETCH_BEER_REQUEST,

	FETCH_SEARCH_BEER_SUCCESS,
	FETCH_SEARCH_BEER_ERROR,
	FETCH_SEARCH_BEER_REQUEST,

	BEER_TOGGLE_FAVOURITE,
}